name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ALLURE_RESULTS_DIR: allure-results/
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install Allure Reports
      run: |
        npm install -D allure-commandline
        npx allure generate ./allure-results --clean
    - name: Run Playwright tests
      run: npx playwright test
    - name: Generate Allure report
      if: always()
      run: npx allure generate allure-results -o allure-report --clean
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
